export const SHOW_TOUIT_DETAILS = 'SHOW_TOUIT_DETAILS';
export const SHOW_USER_PROFILE = 'SHOW_USER_PROFILE';
export const SHOW_EDIT_TOUIT = 'SHOW_EDIT_TOUIT';
export const SHOW_CONFIRM_DELETE_TOUIT = 'SHOW_CONFIRM_DELETE_TOUIT';
